<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-sql/blob/main/day27_sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Today's topic
Using the single character wildcard_with LIKE

In [ ]:
#Display customers whose customer_name starts with "A" and has exactly one more character
pd.read_sql("""
SELECT *
FROM customers
WHERE first_name LIKE 'A_';
""", conn)

Empty DataFrame
Columns: [customer_id, first_name, last_name, email, phone, city]
Index: []

In [ ]:
#Display employees whose first_name has exactly five characters
pd.read_sql("""
SELECT *
FROM employees
WHERE first_name LIKE '_____';
""", conn)

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,1,Aarav,Patel,1,2020-07-10,47500.0,HR Executive,Chennai,aarav.patel1@company.com
1,5,Priya,Das,5,2020-01-29,120000.0,Sales Executive,Mumbai,priya.das5@company.com
2,7,Rahul,Roy,7,2019-02-23,90000.0,Support Engineer,Mumbai,rahul.roy7@company.com
3,16,Karan,Taylor,6,2021-01-27,117500.0,Operations Analyst,Pune,karan.taylor16@company.com
4,17,Rohan,Singh,7,2022-04-21,52500.0,Support Engineer,Mumbai,rohan.singh17@company.com
5,18,Sneha,Sharma,8,2020-01-20,50000.0,Legal Advisor,Bangalore,sneha.sharma18@company.com
6,19,David,Singh,9,2021-04-21,62500.0,Data Engineer,Pune,david.singh19@company.com
7,21,Arjun,Taylor,1,2021-09-03,42500.0,HR Executive,Bangalore,arjun.taylor21@company.com
8,23,Kabir,Sharma,3,2023-05-02,105000.0,Software Engineer,Mumbai,kabir.sharma23@company.com
9,24,Meera,Singh,4,2021-07-03,112500.0,Marketing Executive,Hyderabad,meera.singh24@company.com
10,26,Nisha,Sharma,6,2023-08-06,110000.0,Operations Analyst,Pune,nisha.sharma26@company.com
11,28,Grace,Brown,8,2023-03-29,40000.0,Legal Advisor,Bangalore,grace.brown28@company.com
12,29,Aryan,Das,9,2022-12-19,70000.0,Data Engineer,Hyderabad,aryan.das29@company.com
13,30,Pooja,Sharma,10,2020-05-02,120000.0,Security Analyst,Pune,pooja.sharma30@company.com

In [ ]:
#Display products whose product_name starts with "s" followed by exactly one character and then any remaining characters
pd.read_sql("""
SELECT *
FROM products
WHERE product_name LIKE 'S_%';
""", conn)

Empty DataFrame
Columns: [product_id, product_name, category, price, stock_quantity]
Index: []

In [ ]:
#Display departments whose department_name has "e" as the second character
pd.read_sql("""
SELECT *
FROM departments
WHERE department_name LIKE '_e%';
""", conn)

   department_id department_name  manager_id location    budget
0              8           Legal           8    Delhi  280000.0
1             10        Security          10  Kolkata  220000.0

In [ ]:
#find customers whose city starts with "B" has exactly one unknown character and then any remaining character
pd.read_sql("""
SELECT *
FROM customers
WHERE city LIKE 'B_%';
""", conn)

   customer_id first_name last_name              email       phone       city
0            1      Akash    Sharma    akash1@mail.com  9666696518  Bangalore
1            2       Ritu       Das     ritu2@mail.com  9627404182  Bangalore
2           11      Akash     Patel   akash11@mail.com  9719551111  Bangalore
3           16     Anjali     Singh  anjali16@mail.com  9118811611  Bangalore