<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-sql/blob/main/Day24_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Today's topic
Finding text using the LIKE operator

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Display all customers whose customer_name starts with the letter "A"
pd.read_sql("""
SELECT *
FROM customers
WHERE first_name LIKE 'A%';
""", conn)

    customer_id first_name last_name              email       phone       city
0             1      Akash    Sharma    akash1@mail.com  9666696518  Bangalore
1             6     Anjali     Singh   anjali6@mail.com  9693986973       Pune
2            10      Aisha     Kumar   aisha10@mail.com  9332083015    Chennai
3            11      Akash     Patel   akash11@mail.com  9719551111  Bangalore
4            16     Anjali     Singh  anjali16@mail.com  9118811611  Bangalore
5            20      Aisha     Kumar   aisha20@mail.com  9659589923      Delhi
6            21      Akash    Sharma   akash21@mail.com  9124393190       Pune
7            26     Anjali     Kumar  anjali26@mail.com  9988357959      Delhi
8            30      Aisha       Das   aisha30@mail.com  9627755893     Mumbai
9            31      Akash     Gupta   akash31@mail.com  9750806415    Kolkata
10           36     Anjali     Gupta  anjali36@mail.com  9310837702    Chennai
11           40      Aisha    Taylor   aisha40@mail.com  9829603810    Kolkata

In [ ]:
#Display all employees whose first_name starts with the letter "J"
pd.read_sql("""
SELECT *
FROM employees
WHERE first_name LIKE 'J%';
""", conn)

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,9,John,Brown,9,2021-11-22,45000.0,Data Engineer,Pune,john.brown9@company.com

In [ ]:
#Display all products whose product_name starts with the letter "s"
pd.read_sql("""
SELECT *
FROM products
WHERE product_name LIKE 'S%';
""", conn)

Empty DataFrame
Columns: [product_id, product_name, category, price, stock_quantity]
Index: []

In [ ]:
#Display all departments whose department_name starts with the letter "h"
pd.read_sql("""
SELECT *
FROM departments
WHERE department_name LIKE 'H%';
""", conn)

   department_id department_name  manager_id   location    budget
0              1              HR           1  Bangalore  300000.0

In [ ]:
#Display all customers whose city starts with the letter "B"
pd.read_sql("""
SELECT *
FROM customers
WHERE city LIKE 'B%';
""", conn)

   customer_id first_name last_name              email       phone       city
0            1      Akash    Sharma    akash1@mail.com  9666696518  Bangalore
1            2       Ritu       Das     ritu2@mail.com  9627404182  Bangalore
2           11      Akash     Patel   akash11@mail.com  9719551111  Bangalore
3           16     Anjali     Singh  anjali16@mail.com  9118811611  Bangalore