<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-sql/blob/main/Day29_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Today's topic
Mixed practice with LIKE,% and _ wildcard

In [ ]:
#Display customers whose customer_name starts with the letter "s"
pd.read_sql("""
SELECT *
FROM customers
WHERE first_name LIKE 'S%';
""", conn)

   customer_id first_name last_name              email       phone     city
0            4     Simran       Das   simran4@mail.com  9979444461  Chennai
1           14     Simran    Taylor  simran14@mail.com  9604314504  Kolkata
2           24     Simran       Das  simran24@mail.com  9185583902     Pune
3           34     Simran    Wilson  simran34@mail.com  9642604350     Pune

In [ ]:
#Display employees whose first_name ends with the letter "n"
pd.read_sql("""
SELECT *
FROM employees
WHERE first_name LIKE '%n';
""", conn)

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,2,Vivaan,Patel,2,2022-01-10,105000.0,Accountant,Bangalore,vivaan.patel2@company.com
1,9,John,Brown,9,2021-11-22,45000.0,Data Engineer,Pune,john.brown9@company.com
2,16,Karan,Taylor,6,2021-01-27,117500.0,Operations Analyst,Pune,karan.taylor16@company.com
3,17,Rohan,Singh,7,2022-04-21,52500.0,Support Engineer,Mumbai,rohan.singh17@company.com
4,21,Arjun,Taylor,1,2021-09-03,42500.0,HR Executive,Bangalore,arjun.taylor21@company.com
5,29,Aryan,Das,9,2022-12-19,70000.0,Data Engineer,Hyderabad,aryan.das29@company.com

In [ ]:
#Display products whose product_name contains the letter "pro"
pd.read_sql("""
SELECT *
FROM products
WHERE product_name LIKE '%pro%';
""", conn)

Empty DataFrame
Columns: [product_id, product_name, category, price, stock_quantity]
Index: []

In [ ]:
#Display department whose department_name has exactly one character before the letter "e"
pd.read_sql("""
SELECT *
FROM departments
WHERE department_name LIKE '_e%';
""", conn)

   department_id department_name  manager_id location    budget
0              8           Legal           8    Delhi  280000.0
1             10        Security          10  Kolkata  220000.0

In [ ]:
#Display customers whose city starts with "B" and ends with "e"
pd.read_sql("""
SELECT *
FROM customers
WHERE city LIKE 'B%e';
""", conn)

   customer_id first_name last_name              email       phone       city
0            1      Akash    Sharma    akash1@mail.com  9666696518  Bangalore
1            2       Ritu       Das     ritu2@mail.com  9627404182  Bangalore
2           11      Akash     Patel   akash11@mail.com  9719551111  Bangalore
3           16     Anjali     Singh  anjali16@mail.com  9118811611  Bangalore