<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-sql/blob/main/Day34_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Today's topic
SUM() function
Goal: learn how to calculate the total value of numeric data using SUM()

In [ ]:
#find the total quantity of all orders
pd.read_sql("""
SELECT SUM(quantity) AS total_quantity
FROM orders;
""", conn)

   total_quantity
0             293

In [ ]:
#find the total stock quantity of all products
pd.read_sql("""
SELECT SUM(stock_quantity) AS total_stock
FROM products;
""", conn)

   total_stock
0          572

In [ ]:
#find the total salary of employees whose department_id is 1
pd.read_sql("""
SELECT SUM(salary) AS total_salary
FROM employees
WHERE department_id = 1;
""", conn)

   total_salary
0      202500.0

In [ ]:
#find the total quantity ordered where the order quantity is greater than 2
pd.read_sql("""
SELECT SUM(quantity) AS total_ordered
FROM orders
WHERE quantity > 2;
""", conn)

   total_ordered
0            227

In [ ]:
#find the total price of all products in the electronics category
pd.read_sql("""
SELECT SUM(price) AS total_price
FROM products
WHERE category = 'Electronics';
""", conn)

  total_price
0        None