<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-sql/blob/main/Day32_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Today's topic
COUNT() with WHERE
Goal: learn how to count only the rows that match a condition

In [ ]:
#count the total number of customers
pd.read_sql("""
SELECT COUNT(*)
FROM customers;
""", conn)

   COUNT(*)
0        40

In [ ]:
#count how many products belong to the electronics category
pd.read_sql("""
SELECT COUNT(*)
FROM products
WHERE category = 'Electronics';
""", conn)

   COUNT(*)
0         0

In [ ]:
#count how many employees work in the sales department using department_id
pd.read_sql("""
SELECT COUNT(*)
FROM employees
WHERE department_id = 1;
""", conn)

   COUNT(*)
0         3

In [ ]:
#count the number of orders placed where the quantity is greater than 3
pd.read_sql("""
SELECT COUNT(*)
FROM orders
WHERE quantity > 3;
""", conn)

   COUNT(*)
0        39

In [ ]:
#count how many employees earn a salary greater than 60000
pd.read_sql("""
SELECT COUNT(*)
FROM employees
WHERE salary > 60000;
""", conn)

   COUNT(*)
0        19