<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-sql/blob/main/Day38_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Today's topic
Using multiple aggregate function together
Goal: learn how to COUNT(), SUM(), AVG(), MIN(), and MAX() in a single query to get a quick summary of your data

In [ ]:
#Display the total number of employees and the minimum and maximum salary
pd.read_sql("""
SELECT COUNT(*) AS total_employees,
       MIN(salary) AS minimum_salary,
       MAX(salary) AS maximum_salary
FROM employees;
""", conn)

   total_employees  minimum_salary  maximum_salary
0               30         40000.0        120000.0

In [ ]:
#Show the total number of products along with the minimum and maximum product price
pd.read_sql("""
SELECT COUNT(*) AS total_products,
       MIN(price) AS minimum_price,
       MAX(price) AS maximum_price
FROM products;
""", conn)

   total_products  minimum_price  maximum_price
0              25         1499.0        91999.0

In [ ]:
#Display the total number of orders, total ordered quantity, and average order quantity
pd.read_sql("""
SELECT COUNT(*) AS total_orders,
       SUM(quantity) AS total_quantity,
       AVG(quantity) AS average_quantity
FROM orders;
""", conn)

   total_orders  total_quantity  average_quantity
0           100             293              2.93

In [ ]:
#For products in the Electronics category, display the total number of products, minimum price, maximum price, and average price
pd.read_sql("""
SELECT COUNT(*) AS total_products,
       MIN(price) AS minimum_price,
       MAX(price) AS maximum_price,
       AVG(price) AS average_price
FROM products
WHERE category = 'Electronics';
""", conn)

   total_products minimum_price maximum_price average_price
0               0          None          None          None