<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-sql/blob/main/day37_sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Today's topic
MAX() function
Goal: learn how to find the largest value in a numeric or date column using MAX()

In [ ]:
#Find the highest salary among all employees
pd.read_sql("""
SELECT MAX(salary) AS highest_salary
FROM employees;
""", conn)

   highest_salary
0        120000.0

In [ ]:
#Find the maximum product price
pd.read_sql("""
SELECT MAX(price) AS max_price
FROM products;
""", conn)

   max_price
0    91999.0

In [ ]:
#Find the latest order date in the orders table.
pd.read_sql("""
SELECT MAX(order_date) AS latest_order_date
FROM orders;
""", conn)

  latest_order_date
0        2026-05-02

In [ ]:
#Find the highest stock quantity for products in the Electronics category
pd.read_sql("""
SELECT MAX(stock_quantity) AS highest_stock
FROM products
WHERE category = 'Electronics';
""", conn)

  highest_stock
0          None

In [ ]:
#Find the highest salary of employees whose department_id is 2
pd.read_sql("""
SELECT MAX(salary) AS highest_salary
FROM employees
WHERE department_id = 2;
""", conn)

   highest_salary
0        105000.0