<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-sql/blob/main/Day31_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Today's topic
Introduction to the COUNT() aggregate function

In [ ]:
#count the total number of employees in the employees table
pd.read_sql("""
SELECT COUNT(*)
FROM employees;
""", conn)

   COUNT(*)
0        30

In [ ]:
#count the total number of departments
pd.read_sql("""
SELECT COUNT(*)
FROM departments;
""", conn)

   COUNT(*)
0        10

In [ ]:
#count the total number of products
pd.read_sql("""
SELECT COUNT(*)
FROM products;
""", conn)

   COUNT(*)
0        25

In [ ]:
#count the total number of customers
pd.read_sql("""
SELECT COUNT(*)
FROM customers;
""", conn)

   COUNT(*)
0        40

In [ ]:
#count the total number of order
pd.read_sql("""
SELECT COUNT(*)
FROM orders;
""", conn)

   COUNT(*)
0       100