<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-sql/blob/main/Day39_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Today's topic
Practice with aggregate function
Goal: strengthen your understanding of COUNT(), SUM(), AVG(), MIN() and MAX() by solving practical business style problem

In [ ]:
#Display the total number of products and the average product price
pd.read_sql("""
SELECT COUNT(*) AS total_products,
       AVG(price) AS average_price
FROM products;
""", conn)

   total_products  average_price
0              25        26099.0

In [ ]:
#Find the total quantity ordered and the maximum quantity ordered from the orders table
pd.read_sql("""
SELECT SUM(quantity) AS total_quantity,
       MAX(quantity) AS maximum_quantity
FROM orders;
""", conn)

   total_quantity  maximum_quantity
0             293                 5

In [ ]:
#Display the minimum, maximum, and average salary of all employees
pd.read_sql("""
SELECT MIN(salary) AS minimum_salary,
       MAX(salary) AS maximum_salary,
       AVG(salary) AS average_salary
FROM employees;
""", conn)

   minimum_salary  maximum_salary  average_salary
0         40000.0        120000.0         80750.0

In [ ]:
#For products in the Electronics category, display the total number of products, total stock quantity, and average product price
pd.read_sql("""
SELECT COUNT(*) AS total_products,
       SUM(stock_quantity) AS total_stock_quantity,
       AVG(price) AS average_price
FROM products
WHERE category = 'Electronics';
""", conn)

   total_products total_stock_quantity average_price
0               0                 None          None

In [ ]:
#For employees whose department_id is 1, display the total employees, total salary, average salary, minimum salary, and maximum salary in a single query
pd.read_sql("""
SELECT COUNT(*) AS total_products,
       SUM(stock_quantity) AS total_stock_quantity,
       AVG(price) AS average_price
FROM products
WHERE category = 'Electronics';
""", conn)

   total_products total_stock_quantity average_price
0               0                 None          None