<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-sql/blob/main/Day35_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Today's topic
AVG() function
Goal: learn how to calculate the average value of numeric data using AVG()

In [ ]:
#find the average salary of all employees
pd.read_sql("""
SELECT AVG(salary) AS average_salary
FROM employees;
""", conn)

   average_salary
0         80750.0

In [ ]:
#find the average price of all products
pd.read_sql("""
SELECT AVG(price) AS average_price
FROM products;
""", conn)

   average_price
0        26099.0

In [ ]:
#find the average quantity ordered in the order table
pd.read_sql("""
SELECT AVG(quantity) AS average_quantity
FROM orders;
""", conn)

   average_quantity
0              2.93

In [ ]:
#find the average salary of employees whose department_id is 2
pd.read_sql("""
SELECT AVG(salary) AS average_salary
FROM employees
WHERE department_id = 2;
""", conn)

   average_salary
0    71666.666667