<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-sql/blob/main/Day33_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Today's topic
COUNT() with condition
Goal: learn how to count only the rows that match a condition using WHERE

In [ ]:
#count how many employees belong to the sales department (department_id = 1)
pd.read_sql("""
SELECT COUNT(*)
FROM employees
WHERE department_id = 1;
""", conn)

   COUNT(*)
0         3

In [ ]:
#count how many products have a price greater than 100
pd.read_sql("""
SELECT COUNT(*)
FROM products
WHERE price > 100;
""", conn)

   COUNT(*)
0        25

In [ ]:
#count how many customers live in delhi
pd.read_sql("""
SELECT COUNT(*)
FROM customers
WHERE city = 'Delhi';
""", conn)

   COUNT(*)
0         6

In [ ]:
#count the number of orders where the quantity is greater than 3
pd.read_sql("""
SELECT COUNT(*)
FROM orders
WHERE quantity > 3;
""", conn)

   COUNT(*)
0        39