<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-sql/blob/main/Day36_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [13]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [14]:
#find the lowest product price in the products table
pd.read_sql("""
SELECT MIN(price) AS lowest_price
FROM products;
""", conn)

   lowest_price
0        1499.0

In [15]:
#find the minimum salary among all employees
pd.read_sql("""
SELECT MIN(salary) AS minimum_salary
FROM employees;
""", conn)

   minimum_salary
0         40000.0

In [ ]:
#find the earliest order_date in the orders table
pd.read_sql("""
SELECT MIN(order_date) AS earliest_order_date
FROM orders;
""", conn)

  earliest_order_date
0          2024-01-07

In [16]:
#find the minimum stock quantity for products in the Electronics category
pd.read_sql("""
SELECT MIN(stock_quantity) AS minimum_stock
FROM products
WHERE category = 'Electronics';
""", conn)

  minimum_stock
0          None

In [17]:
#find the earliest hire date of employees whose department_id is 3
pd.read_sql("""
SELECT MIN(stock_quantity) AS minimum_stock
FROM products
WHERE category = 'Electronics';
""", conn)

  minimum_stock
0          None