<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-sql/blob/main/Day40_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Today's topic
Aggregate function - final practice

In [ ]:
#Display the total number of employees and the highest salary
pd.read_sql("""
SELECT COUNT(*) AS total_employees,
       MAX(salary) AS highest_salary
FROM employees;
""", conn)

   total_employees  highest_salary
0               30        120000.0

In [ ]:
#Find the total stock quantity and the average product price from the products table
pd.read_sql("""
SELECT SUM(stock_quantity) AS total_stock_quantity,
       AVG(price) AS average_price
FROM products;
""", conn)

   total_stock_quantity  average_price
0                   572        26099.0

In [ ]:
#Display the total number of orders, the minimum quantity, and the maximum quantity ordered
pd.read_sql("""
SELECT COUNT(*) AS total_orders,
       MIN(quantity) AS minimum_quantity,
       MAX(quantity) AS maximum_quantity
FROM orders;
""", conn)

   total_orders  minimum_quantity  maximum_quantity
0           100                 1                 5

In [ ]:
#For products in the Electronics category, display the total number of products, total stock quantity, average price, lowest price, and highest price
pd.read_sql("""
SELECT COUNT(*) AS total_products,
       SUM(stock_quantity) AS total_stock_quantity,
       AVG(price) AS average_price,
       MIN(price) AS lowest_price,
       MAX(price) AS highest_price
FROM products
WHERE category = 'Electronics';
""", conn)

,total_products,total_stock_quantity,average_price,lowest_price,highest_price
0,0,None,None,None,None

In [ ]:
#For employees whose department_id is 3, display the total number of employees, total salary, average salary, minimum salary and maximum salary in one query
pd.read_sql("""
SELECT COUNT(*) AS total_employees,
       SUM(salary) AS total_salary,
       AVG(salary) AS average_salary,
       MIN(salary) AS minimum_salary,
       MAX(salary) AS maximum_salary
FROM employees
WHERE department_id = 3;
""", conn)